export const ROUTE = {
  home: '/home',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: (token: string) => `/reset-password/${token}`,
  cart: '/cart',
  checkout: '/order/checkout',
  product: (id: number) => `/product/${id}`,
  profile: (tab: 'info' | 'orders' | 'claims' = 'info') => `/profile?tab=${tab}`,
  claim: '/claim',
  inbox: '/inbox',
  demoInbox: '/demo-inbox',
  claimEvidence: (id: number) => `/profile/claims/${id}/evidence`,
  claimDelete: (id: number) => `/profile/claims/${id}/delete`,
  claimRestore: (id: number) => `/profile/claims/${id}/restore`,
  orderSuccess: (orderId: string) => `/order/success?order_id=${encodeURIComponent(orderId)}`,
  invoice: (orderId: string) => `/order/invoice/${orderId}`,
  testResetStock: '/api/test/reset-stock',
  health: '/health',
  healthDb: '/health/db'
} as const;
