export const TEST_ID = {
  nav: {
    profileLink: 'nav-profile-link',
    logoutLink: 'nav-logout-link',
    loginLink: 'nav-login-link',
    demoInboxLink: 'nav-demo-inbox-link'
  },
  auth: {
    loginPage: 'login-page',
    loginUsernameInput: 'login-username-input',
    loginPasswordInput: 'login-password-input',
    loginSubmitBtn: 'login-submit-btn',
    loginError: 'login-error',
    loginSuccess: 'login-success',
    loginCreateAccountLink: 'login-create-account-link',
    loginForgotPasswordLink: 'login-forgot-password-link',
    registerPage: 'register-page',
    registerUsernameInput: 'register-username-input',
    registerEmailInput: 'register-email-input',
    registerPasswordInput: 'register-password-input',
    registerConfirmPasswordInput: 'register-confirm-password-input',
    registerSubmitBtn: 'register-submit-btn',
    registerError: 'register-error',
    forgotPasswordPage: 'forgot-password-page',
    forgotPasswordEmailInput: 'forgot-password-email-input',
    forgotPasswordSubmitBtn: 'forgot-password-submit-btn',
    forgotPasswordSuccess: 'forgot-password-success',
    forgotPasswordError: 'forgot-password-error',
    forgotPasswordDemoInboxLink: 'forgot-password-demo-inbox-link',
    resetPasswordPage: 'reset-password-page',
    resetPasswordInput: 'reset-password-input',
    resetPasswordConfirmInput: 'reset-password-confirm-input',
    resetPasswordSubmitBtn: 'reset-password-submit-btn',
    resetPasswordError: 'reset-password-error'
  },
  catalog: {
    page: 'catalog-page',
    title: 'catalog-title',
    emptyState: 'catalog-empty-state',
    productsGrid: 'catalog-products-grid',
    filterSearchInput: 'filter-search-input',
    filterCategorySelect: 'filter-category-select',
    filterMinPriceInput: 'filter-min-price-input',
    filterMaxPriceInput: 'filter-max-price-input',
    filterSortSelect: 'filter-sort-select',
    applyBtn: 'catalog-apply-btn',
    resetBtn: 'catalog-reset-btn',
    pageBtn: (page: number) => `catalog-page-${page}`,
    productCard: (id: number) => `product-card-${id}`,
    productViewDetails: (id: number) => `product-view-details-${id}`
  },
  product: {
    page: 'product-page',
    title: 'product-title',
    stock: 'product-stock',
    outOfStock: 'product-out-of-stock',
    availableStock: 'product-available-stock',
    qtyInput: 'product-qty',
    addToCartBtn: 'product-add-to-cart'
  },
  cart: {
    page: 'cart-page',
    title: 'cart-title',
    emptyState: 'cart-empty-state',
    success: 'cart-success',
    error: 'cart-error',
    checkoutLink: 'cart-checkout-link',
    row: (id: number) => `cart-row-${id}`,
    qtyInput: (id: number) => `cart-qty-${id}`,
    clearBtn: 'cart-clear-btn',
    couponInput: 'cart-coupon-input',
    applyCouponBtn: 'cart-apply-coupon-btn',
    removeCouponBtn: 'cart-remove-coupon-btn',
    couponCode: 'cart-coupon-code',
    discountRow: 'cart-discount-row',
    subtotal: 'cart-subtotal',
    grandTotal: 'cart-grand-total'
  },
  checkout: {
    page: 'checkout-page',
    title: 'checkout-title',
    error: 'checkout-error',
    success: 'checkout-success',
    nameInput: 'checkout-name-input',
    emailInput: 'checkout-email-input',
    addressInput: 'checkout-address-input',
    cardNumberInput: 'checkout-card-number-input',
    expMonthInput: 'checkout-exp-month-input',
    expYearInput: 'checkout-exp-year-input',
    cvcInput: 'checkout-cvc-input',
    paymentStatus: 'checkout-payment-status',
    payButton: 'mock-pay-btn'
  },
  orderSuccess: {
    page: 'order-success-page',
    title: 'order-success-title',
    orderId: 'order-success-order-id',
    invoiceLink: 'order-success-view-invoice-link'
  },
  profile: {
    page: 'profile-page',
    title: 'profile-title',
    tabInfo: 'profile-tab-info',
    tabOrders: 'profile-tab-orders',
    tabClaims: 'profile-tab-claims',
    infoSection: 'profile-info-section',
    emailInput: 'profile-email-input',
    addressInput: 'profile-address-input',
    phoneInput: 'profile-phone-input',
    saveBtn: 'profile-save-btn',
    success: 'profile-success',
    error: 'profile-error',
    ordersSection: 'profile-orders-section',
    ordersInboxTab: 'orders-box-inbox-tab',
    ordersTrashTab: 'orders-box-trash-tab',
    orderCard: (orderId: string) => `order-card-${orderId}`,
    orderInvoiceLink: (orderId: string) => `order-invoice-link-${orderId}`,
    orderTrashBtn: (orderId: string) => `order-trash-btn-${orderId}`,
    orderRestoreBtn: (orderId: string) => `order-restore-btn-${orderId}`,
    orderDestroyBtn: (orderId: string) => `order-destroy-btn-${orderId}`,
    claimsSection: 'profile-claims-section',
    claimsInboxTab: 'claims-box-inbox-tab',
    claimsTrashTab: 'claims-box-trash-tab',
    claimsFileNewLink: 'claims-file-new-link',
    claimsEmptyState: 'claims-empty-state',
    claimCard: (id: number) => `claim-card-${id}`,
    claimTrashBtn: (id: number) => `claim-trash-btn-${id}`,
    claimRestoreBtn: (id: number) => `claim-restore-btn-${id}`,
    claimDestroyBtn: (id: number) => `claim-destroy-btn-${id}`,
    claimEvidenceLink: (id: number) => `claim-evidence-link-${id}`
  },
  claim: {
    page: 'claim-page',
    title: 'claim-title',
    invoiceIdInput: 'claim-invoice-id-input',
    descriptionInput: 'claim-description-input',
    imageInput: 'claim-image-input',
    submitBtn: 'claim-submit-btn',
    error: 'claim-error'
  },
  inbox: {
    page: 'inbox-page',
    title: 'inbox-title',
    messageCount: 'inbox-message-count',
    tabInbox: 'inbox-tab-inbox',
    tabTrash: 'inbox-tab-trash',
    emptyState: 'inbox-empty-state',
    detailSubject: 'inbox-detail-subject',
    detailBody: 'inbox-detail-body',
    detailEmpty: 'inbox-detail-empty',
    emptyTrashBtn: 'inbox-empty-trash-btn',
    emailItem: (id: number) => `inbox-email-item-${id}`,
    emailLink: (id: number) => `inbox-email-link-${id}`,
    trashBtn: (id: number) => `inbox-trash-btn-${id}`,
    restoreBtn: (id: number) => `inbox-restore-btn-${id}`,
    destroyBtn: (id: number) => `inbox-destroy-btn-${id}`
  },
  invoice: {
    page: 'invoice-page',
    title: 'invoice-title',
    orderId: 'invoice-order-id',
    subtotal: 'invoice-subtotal',
    discount: 'invoice-discount',
    tax: 'invoice-tax',
    deliveryFee: 'invoice-delivery-fee',
    grandTotal: 'invoice-grand-total',
    backOrderHistoryLink: 'invoice-back-order-history-link'
  },
  common: {
    notFoundPage: 'not-found-page',
    notFoundTitle: 'not-found-title',
    notFoundMessage: 'not-found-message'
  }
} as const;
